### ISSUE TITLE
Sample assets

### ISSUE THREAD

**Issue by paulocoutinhox** [aesophor/vigilante#1]
Hi,

Can you add some sample assets?

Without this, is hard to find/create the required images.

Thanks.

**Comment by aismann** [comment]
> Hi,
> Can you add some sample assets?
> Without this, is hard to find/create the required images.
> Thanks.

I found this sentence in the history:
_I'm sorry, but I really cannot upload the resources folder (directory) since it contains spritesheets/sprites which was purchased from other pixel artists. Thanks for your understanding._

**Comment by aesophor** [comment]
@aismann Thanks so much!
